name: Lint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v1
        with:
          eslintArgs: '--config=./.eslintrc.js'
          extensions: 'ts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
